quarkus.banner.enabled=false
quarkus.log.level=WARN
quarkus.log.category."org.hoohoot".level=INFO

odoo.url=http://localhost:8069
odoo.database=odoo
odoo.login=admin
odoo.password=admin
odoo.timeout-seconds=60

brevo.url=https://api.brevo.com
brevo.api-key=changeme
